# Generated by Django 6.0.4 on 2026-04-19 08:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_inventorybatch_created_at_inventorybatch_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expense_type', models.CharField(choices=[('OTHER', 'Other Expense'), ('BATCH', 'Batch Expense'), ('OPERATING', 'Operating Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, choices=[('SALARY', 'Staff Salary'), ('COMMISSION', 'Commission'), ('BOOSTING', 'Boosting'), ('RENT', 'Rent'), ('UTILITY', 'Utility'), ('OTHER', 'Other')], default='', max_length=30)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_rows', to='inventory.inventorybatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_expenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'permissions': [('can_create_other_expense', 'Can create other expense'), ('can_create_batch_expense', 'Can create batch expense'), ('can_create_operating_expense', 'Can create operating expense')],
            },
        ),
    ]
