# Generated by Django 6.0.4 on 2026-04-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_expense_options_expense_batch_cost_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('view_finance_nav', 'Can view finance navbar'), ('view_expense_summary_nav', 'Can view expense summary navbar'), ('view_other_expense_nav', 'Can view other expense navbar'), ('view_batch_expense_nav', 'Can view batch expense navbar'), ('view_operating_expense_nav', 'Can view operating expense navbar'), ('view_profit_dashboard_nav', 'Can view profit dashboard navbar')]},
        ),
    ]
