# Generated by Django 6.0.4 on 2026-08-04 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_expense_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_status',
            field=models.CharField(choices=[('PENDING', 'Pending Cost'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='fabric_receipt_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='expense',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='source_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='expense',
            name='stock_source_type',
            field=models.CharField(blank=True, choices=[('INVENTORY', 'Inventory Batch'), ('FABRIC', 'Fabric Stock In')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, choices=[('GRAB', 'Grab Delivery'), ('UTILITY', 'Utility'), ('FOOD', 'Food'), ('STATIONERY', 'Stationery'), ('REPAIR', 'Repair'), ('TRANSPORT', 'Transport'), ('SMALL_PURCHASE', 'Small Purchase'), ('OTHER', 'Other'), ('SALARY', 'Staff Salary'), ('COMMISSION', 'Staff Commission'), ('CLOTH_CUTTING', 'Cloth Cutting Expense'), ('RENT', 'Rent'), ('ELECTRICITY', 'Electricity'), ('INTERNET', 'Internet'), ('MARKETING', 'Marketing'), ('EQUIPMENT', 'Equipment'), ('OTHER', 'Other')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('OTHER', 'Other Expense'), ('BATCH', 'Stock In Expense'), ('OPERATING', 'Operating Expense')], max_length=20),
        ),
    ]
