# Generated by Django 6.0.4 on 2026-07-02 17:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0007_stockledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SewingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FabricReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('supplier', models.CharField(max_length=150)),
                ('received_date', models.DateField(default=django.utils.timezone.localdate)),
                ('fabric_name', models.CharField(max_length=150)),
                ('roll_count', models.PositiveIntegerField(default=1)),
                ('total_goods_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('extra_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_fabric_receipts', to='inventory.color')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_fabric_receipts_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_fabric_receipts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_date', '-id'],
                'permissions': [('view_production_nav', 'Can view production navbar'), ('view_production_cost', 'Can view production costs'), ('manage_production_payments', 'Can manage production payments')],
            },
        ),
        migrations.CreateModel(
            name='FabricRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_code', models.CharField(max_length=70, unique=True)),
                ('original_qty', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('remaining_qty', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('FULL', 'Full'), ('PARTIAL', 'Partial'), ('USED', 'Used')], default='FULL', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rolls', to='production.fabricreceipt')),
            ],
            options={
                'ordering': ['receipt__fabric_name', 'receipt__color__name', 'roll_code'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payable_type', models.CharField(choices=[('SEWER', 'Sewing Partner'), ('STAFF', 'Production Staff')], max_length=20)),
                ('payee_name', models.CharField(max_length=150)),
                ('work_type', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_payables_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['payee_name', 'project__project_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('payable_type', models.CharField(choices=[('SEWER', 'Sewing Partner'), ('STAFF', 'Production Staff')], max_length=20)),
                ('payee_name', models.CharField(max_length=150)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('ABA', 'ABA'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('finance_expense_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_payment_batches_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='production.productionpayable')),
                ('payment_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='production.productionpaymentbatch')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('expected_qty', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CUTTING', 'Cutting'), ('CUT_COMPLETE', 'Cut Completed'), ('SENT', 'Sent to Sewing'), ('PARTIAL_RETURN', 'Partially Returned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_projects', to='inventory.color')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_projects_created', to=settings.AUTH_USER_MODEL)),
                ('finished_item', models.ForeignKey(limit_choices_to={'item_type': 'SHIRT'}, on_delete=django.db.models.deletion.PROTECT, related_name='production_projects', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='productionpayable',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='production.productionproject'),
        ),
        migrations.CreateModel(
            name='CuttingSizeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cut_qty', models.PositiveIntegerField(default=0)),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_cut_lines', to='inventory.size')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_sizes', to='production.productionproject')),
            ],
            options={
                'ordering': ['size__sort_order', 'size__id'],
            },
        ),
        migrations.CreateModel(
            name='CuttingRollUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_qty', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('returned_qty', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('roll_qty_before', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('roll_qty_after', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=10)),
                ('applied', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cutting_usages', to='production.fabricroll')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_usages', to='production.productionproject')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SewingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('sent_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('price_per_piece', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('PARTIAL', 'Partially Returned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SENT', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_sewing_jobs_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sewing_jobs', to='production.productionproject')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sewing_jobs', to='production.sewingpartner')),
            ],
            options={
                'ordering': ['-sent_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='productionpayable',
            name='sewing_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='production.sewingjob'),
        ),
        migrations.CreateModel(
            name='SewingJobLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_qty', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.sewingjob')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_sewing_lines', to='inventory.size')),
            ],
            options={
                'ordering': ['size__sort_order', 'size__id'],
            },
        ),
        migrations.CreateModel(
            name='SewingReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('return_date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('STOCKED', 'Confirmed & Stocked In'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('stocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_sewing_returns_created', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='production.sewingjob')),
                ('stock_batch', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_sewing_return', to='inventory.inventorybatch')),
                ('stocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_sewing_returns_stocked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-return_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='productionpayable',
            name='sewing_return',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sewing_payable', to='production.sewingreturn'),
        ),
        migrations.CreateModel(
            name='SewingReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_qty', models.PositiveIntegerField(default=0)),
                ('damaged_qty', models.PositiveIntegerField(default=0)),
                ('missing_qty', models.PositiveIntegerField(default=0)),
                ('sewing_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='production.sewingreturn')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_return_lines', to='inventory.size')),
            ],
            options={
                'ordering': ['size__sort_order', 'size__id'],
            },
        ),
        migrations.AddIndex(
            model_name='fabricroll',
            index=models.Index(fields=['status', 'remaining_qty'], name='production__status_d8fcc1_idx'),
        ),
        migrations.AddIndex(
            model_name='fabricroll',
            index=models.Index(fields=['roll_code'], name='production__roll_co_4e17c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='productionpaymentallocation',
            constraint=models.UniqueConstraint(fields=('payment_batch', 'payable'), name='uniq_payment_batch_payable'),
        ),
        migrations.AddConstraint(
            model_name='cuttingsizeline',
            constraint=models.UniqueConstraint(fields=('project', 'size'), name='uniq_project_cut_size'),
        ),
        migrations.AddConstraint(
            model_name='cuttingrollusage',
            constraint=models.UniqueConstraint(fields=('project', 'roll'), name='uniq_project_fabric_roll'),
        ),
        migrations.AddConstraint(
            model_name='sewingjobline',
            constraint=models.UniqueConstraint(fields=('job', 'size'), name='uniq_sewing_job_size'),
        ),
        migrations.AddIndex(
            model_name='productionpayable',
            index=models.Index(fields=['payable_type', 'payee_name'], name='production__payable_df371e_idx'),
        ),
        migrations.AddConstraint(
            model_name='sewingreturnline',
            constraint=models.UniqueConstraint(fields=('sewing_return', 'size'), name='uniq_sewing_return_size'),
        ),
    ]
