# Generated by Django 6.0.4 on 2026-08-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_fabrictype_alter_productionexpense_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionproject',
            name='additional_fabric_types',
            field=models.ManyToManyField(blank=True, related_name='additional_production_projects', to='production.fabrictype'),
        ),
    ]
