# Generated by Django 6.0.4 on 2026-08-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_sewing_partner_or_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sewingpartner',
            options={'ordering': ['-is_default', 'name']},
        ),
        migrations.AddField(
            model_name='sewingpartner',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Automatically use this sewer for new production sewing jobs.'),
        ),
    ]
