# Generated by Django 6.0.4 on 2026-08-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_sewingpartner_options_sewingpartner_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionproject',
            name='cutting_is_complete',
            field=models.BooleanField(default=False, help_text='Keep false while partial cutting is still continuing. Set true only when no more pieces will be cut.'),
        ),
    ]
