# Generated by Django 6.0.4 on 2026-08-24 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_productionproject_cutting_is_complete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sewingpartner',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='productionproject',
            name='cutting_is_complete',
        ),
        migrations.RemoveField(
            model_name='sewingpartner',
            name='is_default',
        ),
        migrations.AddField(
            model_name='fabricreceipt',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fabricreceipt',
            name='pending_roll_weights',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='fabricreceipt',
            name='purchase_group',
            field=models.CharField(blank=True, db_index=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='fabricreceipt',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fabricreceipt',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_fabric_receipts_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fabricreceipt',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting to Receive'), ('RECEIVED', 'Received')], default='RECEIVED', max_length=20),
        ),
    ]
