# Generated by Django 6.0.4 on 2026-08-18 11:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_staff_employee',
            field=models.BooleanField(default=False, help_text='Enable this user as an office staff member for payroll.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='join_date',
            field=models.DateField(blank=True, help_text='Date this staff member joined the office.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='left_date',
            field=models.DateField(blank=True, help_text='Optional. Date the staff member stopped working.', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='staff_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='StaffPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('first_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('first_payment_date', models.DateField(blank=True, null=True)),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('final_payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('final_payment_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FIRST_PAID', 'First Payment Paid'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_payrolls_created', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-year', '-month', 'staff__user__username'],
            },
        ),
        migrations.CreateModel(
            name='StaffPayrollPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('FIRST', 'First Payment'), ('FINAL', 'Final Payment')], max_length=20)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('ABA', 'ABA'), ('BANK', 'Bank Transfer'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('finance_expense_id', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_payroll_payments_created', to=settings.AUTH_USER_MODEL)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounts.staffpayroll')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffSalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('effective_date', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_salary_records_created', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_history', to='accounts.userprofile')),
            ],
            options={
                'ordering': ['-effective_date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='staffpayroll',
            index=models.Index(fields=['year', 'month', 'status'], name='accounts_st_year_63a131_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffpayroll',
            constraint=models.UniqueConstraint(fields=('staff', 'year', 'month'), name='unique_staff_monthly_payroll'),
        ),
        migrations.AddConstraint(
            model_name='staffpayrollpayment',
            constraint=models.UniqueConstraint(fields=('payroll', 'payment_type'), name='unique_staff_payroll_payment_type'),
        ),
        migrations.AddIndex(
            model_name='staffsalaryhistory',
            index=models.Index(fields=['staff', 'effective_date'], name='accounts_st_staff_i_1c799a_idx'),
        ),
    ]
