# Generated by Django 6.0.4 on 2026-04-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorybatch',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final')], default='FINAL', max_length=20),
        ),
    ]
