# Generated by Django 6.0.4 on 2026-04-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventorybatch_batch_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='hex_code',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sample_style',
            field=models.CharField(blank=True, choices=[('OVERSIZE', 'Oversize'), ('POLO', 'Polo'), ('BOXY', 'Boxy')], default='OVERSIZE', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='batch_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final')], default='DRAFT', max_length=20),
        ),
    ]
