# Generated by Django 6.0.4 on 2026-04-24 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorybatch_created_at_inventorybatch_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(choices=[('SHIRT', 'Shirt'), ('FILM', 'Film'), ('INK', 'Ink'), ('POWDER', 'Powder'), ('MAINTENANCE', 'Maintenance'), ('OTHER', 'Other')], default='SHIRT', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit',
            field=models.CharField(choices=[('PCS', 'PCS'), ('METER', 'Meter'), ('ROLL', 'Roll'), ('BOTTLE', 'Bottle'), ('PACK', 'Pack'), ('KG', 'KG'), ('ML', 'ML'), ('LITER', 'Liter')], default='PCS', max_length=20),
        ),
    ]
