# Generated by Django 6.0.4 on 2026-04-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventoryitem_created_at_inventoryitem_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory/items/'),
        ),
    ]
