# Generated by Django 6.0.4 on 2026-05-15 10:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('CORRECT', 'Correct Count / Opening Balance'), ('STOCK_IN', 'Stock In'), ('ORDER_OUT', 'Order / Invoice Out'), ('ORDER_RESTORE', 'Order / Invoice Restore'), ('ADJUST_IN', 'Adjustment In'), ('ADJUST_OUT', 'Adjustment Out'), ('BATCH_EDIT', 'Batch Edit'), ('BATCH_DELETE', 'Batch Delete'), ('OTHER', 'Other')], max_length=30)),
                ('qty_before', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference_no', models.CharField(blank=True, default='', max_length=80)),
                ('source_type', models.CharField(blank=True, choices=[('CORRECT', 'Correct Count'), ('STOCK_IN', 'Stock In'), ('ORDER', 'Order / Invoice'), ('ADJUSTMENT', 'Adjustment'), ('BATCH', 'Batch'), ('SYSTEM', 'System'), ('OTHER', 'Other')], default='', max_length=50)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('order_id', models.PositiveIntegerField(blank=True, null=True)),
                ('order_no', models.CharField(blank=True, default='', max_length=80)),
                ('batch_no', models.CharField(blank=True, default='', max_length=80)),
                ('is_correct_checkpoint', models.BooleanField(default=False)),
                ('correct_remark', models.CharField(blank=True, default='', max_length=255)),
                ('remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('batch_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_logs', to='inventory.inventorybatchitem')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ledger_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['batch_item', 'created_at'], name='inventory_s_batch_i_b4083e_idx'), models.Index(fields=['movement_type', 'created_at'], name='inventory_s_movemen_534f32_idx'), models.Index(fields=['is_correct_checkpoint', 'created_at'], name='inventory_s_is_corr_2799ec_idx'), models.Index(fields=['reference_no'], name='inventory_s_referen_9681ed_idx'), models.Index(fields=['order_no'], name='inventory_s_order_n_195921_idx'), models.Index(fields=['batch_no'], name='inventory_s_batch_n_1560c6_idx'), models.Index(fields=['source_type', 'source_id'], name='inventory_s_source__df8b4f_idx')],
            },
        ),
    ]
