# Generated by Django 6.0.4 on 2026-08-23 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_supplier_master_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybatch',
            name='cost_added_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='cost_added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_batch_costs_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='cost_is_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorybatch',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_batches_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorybatch',
            name='status',
            field=models.CharField(choices=[('COMING_SOON', 'Coming Soon'), ('RECEIVED', 'Received')], default='RECEIVED', max_length=20),
        ),
    ]
