# Generated by Django 6.0.4 on 2026-04-17 09:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('order_type', models.CharField(choices=[('NIRON', 'Niron'), ('KAMPU', 'Kampu')], default='NIRON', max_length=20)),
                ('customer_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('deadline', models.DateTimeField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('design_file', models.FileField(blank=True, null=True, upload_to='designs/')),
                ('remark', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock_deducted', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('film_meter_per_piece', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('manual_film_meter', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.color')),
                ('film_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_film_items', to='inventory.inventoryitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('shirt_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_shirt_items', to='inventory.inventoryitem')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.size')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumed_qty', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_consumptions', to='inventory.inventorybatchitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consumptions', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_consumptions', to='orders.orderitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
