# Generated by Django 6.0.4 on 2026-04-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_mode',
            field=models.CharField(choices=[('CLOTH', 'Cloth'), ('FILM', 'Film')], default='CLOTH', max_length=20),
        ),
    ]
