# Generated by Django 6.0.4 on 2026-04-17 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_item_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='design_file',
        ),
        migrations.CreateModel(
            name='OrderDesignFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_designs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_files', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
