# Generated by Django 6.0.4 on 2026-04-18 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_design_file_orderdesignfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='done_pcs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='total_pcs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_done', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='orders.order')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
