# Generated by Django 6.0.4 on 2026-04-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_done_pcs_order_total_pcs_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='done_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
