# Generated by Django 6.0.4 on 2026-04-18 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_done_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderprogress',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='orders.orderitem'),
        ),
    ]
