# Generated by Django 6.0.4 on 2026-04-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderprogress_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
