# Generated by Django 6.0.4 on 2026-04-23 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_orderdesign_orderdesignfile_design_orderitem_design'),
    ]

    operations = [
    ]
