# Generated by Django 6.0.4 on 2026-04-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_move_old_data_to_design'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='film_meter_per_piece',
            new_name='film_meter',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item_mode',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='manual_film_meter',
        ),
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('FULL', 'Full Order'), ('FILM_ONLY', 'Film Only'), ('PRINT_ONLY', 'Print Only'), ('HEATPRESS_ONLY', 'Heat Press Only')], db_index=True, default='FULL', max_length=20),
        ),
    ]
