# Generated by Django 6.0.4 on 2026-04-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_rename_film_meter_per_piece_orderitem_film_meter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('FULL', 'Full Order'), ('FILM_ONLY', 'Film Only'), ('PRINT_HEATPRESS', 'Print & Heat Press')], default='FULL', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('CANCEL', 'Cancel')], default='PENDING', max_length=20),
        ),
    ]
