# Generated by Django 6.0.4 on 2026-04-25 04:52

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='done_qty',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))]),
        ),
    ]
