# Generated by Django 6.0.4 on 2026-04-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('FULL', 'Full Order'), ('FILM_ONLY', 'Film Only'), ('PRINT_HEATPRESS', 'Print & Heat Press'), ('RETAIL', 'Retail Sale')], default='FULL', max_length=30),
        ),
    ]
