# Generated by Django 6.0.4 on 2026-04-26 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_image'),
        ('orders', '0019_order_payment_status_alter_order_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='material_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_material_items', to='inventory.inventoryitem'),
        ),
    ]
