# Generated by Django 6.0.4 on 2026-05-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_alter_order_created_by_orderpaymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date shown on invoice. Admin can edit this date.', null=True),
        ),
    ]
