# Generated by Django 6.0.4 on 2026-08-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('FULL', 'Full Order'), ('FILM_ONLY', 'Film Only'), ('PRINT_HEATPRESS', 'Printing Service'), ('RETAIL', 'Retail Sale')], default='FULL', max_length=30),
        ),
    ]
